const routesConfig = [
  {
    id: 'page-1',
    title: 'Usage Dashboard',
    icon: 'home',
    messageId: 'Usage Dashboard',
    type: 'item',
    url: '/sample/page-1',
  },
  {
    id: 'page-2',
    title: 'Calc Builder',
    icon: 'computer',
    messageId: 'Calc Builder',
    type: 'item',
    url: '/sample/page-2',
  },
  {
    id: 'page-3',
    title: 'Debugger',
    messageId: 'Debugger',
    icon: 'settings',
    type: 'item',
    url: '/sample/page-3',
  },
  {
    id: 'page-4',
    title: 'Data Sources',
    messageId: 'Data Sources',
    icon: 'settings',
    type: 'item',
    url: '/sample/page-4',
  },
  {
    id: 'page-5',
    title: 'Users',
    messageId: 'Users',
    icon: 'users',
    type: 'item',
    url: '/sample/page-5',
  },
  {
    id: 'page-6',
    title: 'Installed Versions',
    messageId: 'Installed Versions',
    icon: 'settings',
    type: 'item',
    url: '/sample/page-6',
  },
  {
    id: 'page-7',
    title: 'Audit',
    messageId: 'Audit',
    icon: 'settings',
    type: 'item',
    url: '/sample/page-7',
  },
  {
    id: 'page-8',
    title: 'Copy Config',
    messageId: 'Copy Config',
    icon: 'settings',
    type: 'item',
    url: '/sample/page-8',
  },
  {
    id: 'page-9',
    title: 'Upload/Download',
    messageId: 'Upload/Download',
    icon: 'settings',
    type: 'item',
    url: '/sample/page-9',
  },
  {
    id: 'page-2-1',
    title: 'Tenant',
    messageId: 'Tenant',
    icon: 'settings',
    type: 'item',
    url: '/sample/Admin/Tenant',
  },
];

export default routesConfig;
